"""The Resolve scripting API as data, parsed from the SDK's DaVinciResolveScript.pyi.

The stub ships with every Resolve install and is regenerated by Blackmagic for each release,
so parsing it at runtime keeps dava in step with the installed version instead of a copy
that would drift.

Types are represented as small tuples:

    ("any",)                       unannotated or unrecognised
    ("none",)
    ("prim", "str"|"int"|"float"|"bool")
    ("list", T)
    ("dict", K, V)
    ("union", [T, ...])
    ("literal", [values], alias_name_or_None)
    ("class", "Timeline")          an API object
    ("typeddict", "AppendClipInfo")
    ("const", "TimelineExportType", [constant names])   a resolve.* constant
"""

import ast
import io
import os
import tokenize
from dataclasses import dataclass, field

from .connect import ResolveError, stub_path

PRIMITIVES = {"str", "int", "float", "bool"}
READ_ONLY_PREFIXES = ("Get", "Is", "Has")


@dataclass
class Param:
    name: str
    type: tuple
    type_text: str
    has_default: bool = False
    default: object = None
    default_text: str = ""

    def text(self):
        out = f"{self.name}: {self.type_text}" if self.type_text else self.name
        return f"{out} = {self.default_text}" if self.has_default else out


@dataclass
class Method:
    cls: str
    name: str
    params: list
    returns: tuple
    returns_text: str
    doc: str

    @property
    def qualname(self):
        return f"{self.cls}.{self.name}"

    @property
    def read_only(self):
        return is_read_only_name(self.name)

    def signature(self):
        params = ", ".join(p.text() for p in self.params)
        return f"{self.qualname}({params}) -> {self.returns_text or 'None'}"

    def as_dict(self):
        return {
            "kind": "method",
            "name": self.qualname,
            "signature": self.signature(),
            "doc": self.doc,
            "read_only": self.read_only,
            "params": [
                {"name": p.name, "type": p.type_text, "required": not p.has_default,
                 **({"default": p.default_text} if p.has_default else {})}
                for p in self.params
            ],
            "returns": self.returns_text or "None",
        }


@dataclass
class ApiClass:
    name: str
    doc: str
    methods: dict = field(default_factory=dict)

    def as_dict(self):
        return {
            "kind": "class",
            "name": self.name,
            "doc": self.doc,
            "opaque": not self.methods,
            "methods": [m.signature() for m in self.methods.values()],
        }


@dataclass
class TypedDictSpec:
    name: str
    doc: str
    fields: dict  # name -> (type, type_text, doc)

    def as_dict(self):
        return {
            "kind": "typeddict",
            "name": self.name,
            "doc": self.doc,
            "fields": [{"name": n, "type": t_text, "doc": d} for n, (_, t_text, d) in self.fields.items()],
        }


@dataclass
class Alias:
    name: str
    kind: str  # "literal" or "constant"
    values: list
    doc: str

    def as_dict(self):
        key = "values" if self.kind == "literal" else "constants"
        return {"kind": f"{self.kind}-alias", "name": self.name, "doc": self.doc, key: self.values}


def is_read_only_name(method_name):
    return method_name.startswith(READ_ONLY_PREFIXES)


def _docstring_after(body, index):
    """Return the string literal that directly follows body[index], if any."""
    if index + 1 < len(body):
        nxt = body[index + 1]
        if isinstance(nxt, ast.Expr) and isinstance(nxt.value, ast.Constant) and isinstance(nxt.value.value, str):
            return nxt.value.value.strip()
    return ""


def _constant_names(doc):
    """Parse 'One of the resolve.* constants: A, B, C' into [A, B, C]."""
    _, sep, tail = doc.partition("constants:")
    if not sep:
        return []
    return [name.strip() for name in tail.split(",") if name.strip()]


class Spec:
    def __init__(self, source, path=None):
        self.path = path
        self.classes = {}
        self.typeddicts = {}
        self.aliases = {}
        self.constants = {}  # constant name -> alias name
        # Functional TypedDicts document their fields in trailing comments: line number -> comment text.
        self._comments = {
            tok.start[0]: tok.string.lstrip("#").strip()
            for tok in tokenize.generate_tokens(io.StringIO(source).readline)
            if tok.type == tokenize.COMMENT
        }
        self._parse(ast.parse(source))

    # -- parsing ---------------------------------------------------------------

    def _parse(self, tree):
        body = tree.body
        # Pass 1: learn every name so annotations can refer forward.
        for index, node in enumerate(body):
            if isinstance(node, ast.ClassDef):
                bases = {ast.unparse(b) for b in node.bases}
                doc = ast.get_docstring(node) or ""
                if "TypedDict" in bases:
                    self.typeddicts[node.name] = TypedDictSpec(node.name, doc, {})
                else:
                    self.classes[node.name] = ApiClass(node.name, doc)
            elif isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
                name = node.targets[0].id
                value = node.value
                if isinstance(value, ast.Subscript) and ast.unparse(value.value) == "Literal":
                    self.aliases[name] = Alias(name, "literal", self._literal_values(value), "")
                elif isinstance(value, ast.Call) and ast.unparse(value.func) == "TypedDict":
                    self.typeddicts[name] = TypedDictSpec(name, "", {})
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                if ast.unparse(node.annotation) == "TypeAlias":
                    doc = _docstring_after(body, index)
                    self.aliases[node.target.id] = Alias(node.target.id, "constant", _constant_names(doc), doc)

        # Pass 2: fill in members now that every name is known.
        for node in body:
            if isinstance(node, ast.ClassDef) and node.name in self.typeddicts:
                self._parse_typeddict_class(node)
            elif isinstance(node, ast.ClassDef):
                self._parse_api_class(node)
            elif isinstance(node, ast.Assign) and isinstance(node.value, ast.Call) and node.targets[0].id in self.typeddicts:
                self._parse_functional_typeddict(node.targets[0].id, node.value)

    def _literal_values(self, subscript):
        inner = subscript.slice
        elements = inner.elts if isinstance(inner, ast.Tuple) else [inner]
        return [ast.literal_eval(e) for e in elements]

    def _parse_typeddict_class(self, node):
        spec = self.typeddicts[node.name]
        for index, item in enumerate(node.body):
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                spec.fields[item.target.id] = (
                    self.type_of(item.annotation), self._text(item.annotation), _docstring_after(node.body, index)
                )

    def _parse_functional_typeddict(self, name, call):
        spec = self.typeddicts[name]
        mapping = call.args[1] if len(call.args) > 1 else None
        if isinstance(mapping, ast.Dict):
            for key, value in zip(mapping.keys, mapping.values):
                doc = self._comments.get(value.end_lineno, "")
                spec.fields[ast.literal_eval(key)] = (self.type_of(value), self._text(value), doc)

    def _parse_api_class(self, node):
        cls = self.classes[node.name]
        for index, item in enumerate(node.body):
            if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                cls.methods[item.name] = self._method(node.name, item)
            elif isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                alias = self._text(item.annotation)
                if alias in self.aliases:
                    self.constants[item.target.id] = alias

    def _method(self, cls_name, func):
        args = func.args.args[1:]  # drop self
        defaults = func.args.defaults
        first_default = len(args) - len(defaults)
        params = []
        for position, arg in enumerate(args):
            has_default = position >= first_default
            default_node = defaults[position - first_default] if has_default else None
            default = ast.literal_eval(default_node) if has_default else None
            if arg.annotation is not None:
                type_, text = self.type_of(arg.annotation), self._text(arg.annotation)
            elif has_default and type(default).__name__ in PRIMITIVES:
                type_, text = ("prim", type(default).__name__), type(default).__name__
            else:
                type_, text = ("any",), ""
            params.append(Param(arg.arg, type_, text, has_default, default,
                                ast.unparse(default_node) if has_default else ""))
        returns = self.type_of(func.returns) if func.returns is not None else ("none",)
        returns_text = self._text(func.returns) if func.returns is not None else ""
        return Method(cls_name, func.name, params, returns, returns_text, ast.get_docstring(func) or "")

    @staticmethod
    def _text(node):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        return ast.unparse(node)

    def type_of(self, node):
        """Translate an annotation AST node into the tuple type model."""
        if node is None:
            return ("any",)
        if isinstance(node, ast.Constant):
            if node.value is None:
                return ("none",)
            if isinstance(node.value, str):  # forward reference such as 'MediaPoolItem'
                return self.type_of(ast.parse(node.value, mode="eval").body)
            return ("any",)
        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
            members = []
            for side in (node.left, node.right):
                t = self.type_of(side)
                members.extend(t[1] if t[0] == "union" else [t])
            return ("union", members)
        if isinstance(node, ast.Subscript):
            head = ast.unparse(node.value)
            args = node.slice.elts if isinstance(node.slice, ast.Tuple) else [node.slice]
            if head == "list":
                return ("list", self.type_of(args[0]))
            if head == "dict":
                return ("dict", self.type_of(args[0]), self.type_of(args[1]) if len(args) > 1 else ("any",))
            if head == "Literal":
                return ("literal", [ast.literal_eval(a) for a in args], None)
            return ("any",)
        if isinstance(node, ast.Name):
            name = node.id
            if name in PRIMITIVES:
                return ("prim", name)
            if name == "list":
                return ("list", ("any",))
            if name == "dict":
                return ("dict", ("any",), ("any",))
            if name in self.classes:
                return ("class", name)
            if name in self.typeddicts:
                return ("typeddict", name)
            if name in self.aliases:
                alias = self.aliases[name]
                if alias.kind == "literal":
                    return ("literal", alias.values, name)
                return ("const", name, alias.values)
        return ("any",)

    # -- queries ---------------------------------------------------------------

    def method(self, cls_name, method_name):
        cls = self.classes.get(cls_name)
        return cls.methods.get(method_name) if cls else None

    def describe(self, name):
        """Describe a class, Class.Method, TypedDict, alias or constant by name."""
        if "." in name:
            cls_name, _, method_name = name.partition(".")
            method = self.method(cls_name, method_name)
            if method is None:
                raise ResolveError(f"No API method {name!r}. Try 'dava api search {method_name}'.")
            result = method.as_dict()
            result["types"] = {t: self.describe(t) for t in self.referenced_types(method)}
            return result
        if name in self.classes:
            return self.classes[name].as_dict()
        if name in self.typeddicts:
            return self.typeddicts[name].as_dict()
        if name in self.aliases:
            return self.aliases[name].as_dict()
        if name in self.constants:
            return {"kind": "constant", "name": name, "alias": self.constants[name],
                    "usage": f"pass the string {name!r} wherever a {self.constants[name]} is expected"}
        raise ResolveError(f"Nothing named {name!r} in the API. Try 'dava api search {name}'.")

    def referenced_types(self, method):
        """Names of TypedDicts and aliases a method's parameters use, so one describe call is enough."""
        found = []

        def walk(t):
            kind = t[0]
            if kind == "typeddict" and t[1] not in found:
                found.append(t[1])
                for field_type, _, _ in self.typeddicts[t[1]].fields.values():
                    walk(field_type)
            elif kind == "literal" and t[2] and t[2] not in found:
                found.append(t[2])
            elif kind == "const" and t[1] not in found:
                found.append(t[1])
            elif kind == "list":
                walk(t[1])
            elif kind == "dict":
                walk(t[1])
                walk(t[2])
            elif kind == "union":
                for member in t[1]:
                    walk(member)

        for param in method.params:
            walk(param.type)
        return found

    def search(self, query, limit=50):
        """Case-insensitive search over method names and docs, types and constants."""
        words = query.lower().split()

        def hit(*texts):
            blob = " ".join(texts).lower()
            return all(word in blob for word in words)

        results = []
        for cls in self.classes.values():
            for method in cls.methods.values():
                if hit(method.qualname, method.doc):
                    # Name matches rank above doc-only matches.
                    rank = 0 if hit(method.qualname) else 1
                    results.append((rank, {"kind": "method", "name": method.qualname,
                                           "signature": method.signature(), "doc": method.doc}))
        for td in self.typeddicts.values():
            if hit(td.name, td.doc, " ".join(td.fields)):
                results.append((2, {"kind": "typeddict", "name": td.name, "doc": td.doc}))
        for alias in self.aliases.values():
            if hit(alias.name, alias.doc):
                results.append((2, {"kind": f"{alias.kind}-alias", "name": alias.name, "doc": alias.doc}))
        for const, alias in self.constants.items():
            if hit(const):
                results.append((3, {"kind": "constant", "name": const, "alias": alias}))
        results.sort(key=lambda pair: pair[0])
        return [entry for _, entry in results[:limit]]

    def as_dict(self):
        return {
            "source": self.path,
            "classes": {name: cls.as_dict() for name, cls in self.classes.items()},
            "methods": {m.qualname: m.as_dict() for c in self.classes.values() for m in c.methods.values()},
            "typeddicts": {name: td.as_dict() for name, td in self.typeddicts.items()},
            "aliases": {name: alias.as_dict() for name, alias in self.aliases.items()},
            "constants": dict(self.constants),
        }


_cache = {}


def load_spec(path=None):
    """Parse (once per process) the installed stub, or raise ResolveError if it is missing."""
    path = path or stub_path()
    if path not in _cache:
        if not path or not os.path.isfile(path):
            raise ResolveError(
                f"API definition not found at {path!r}. It ships with DaVinci Resolve 19+ under "
                "Developer/Scripting; set RESOLVE_SCRIPT_API to that folder."
            )
        with open(path, encoding="utf-8") as handle:
            _cache[path] = Spec(handle.read(), path)
    return _cache[path]
